### ISSUE TITLE
Kan ikke starte serveren

### ISSUE THREAD

**Issue by alex470g** [Phasfeldt/ByHyperionFX_Public#1]
Hej allesammen, jeg ved godt at Phasfeldt at han ikke ville hjælpe med fejl og sådanne, men det kunne være noget vidste hvordan man fixede det. Det er fordi at jeg prøver at starte Hyperion Serveren men kan ikke den siger i RunServer 1 til 4 at "'FXServer' is not recognized as an internal or external command,
operable program or batch file." Har prøvet næsten alt og ved ikke hvad jeg skal gøre håber det ville være nogle flinke mennesker derude som kan hjælpe :)

**Comment by kimtheis** [comment]
Hej tror ikke du har fx server instaleret her er det https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/1110-04af75ed55b418aea5ad1483bc07fdaa5caed76c/server.zip

hvis du evt har brug for mere hjælp kontakt mig på Discord mrcool1575#5674

**Comment by ruhan0405** [comment]
Kimtheis kan du eventuelt add mig. Har samme problem Rune! ;)#9204

**Comment by RexTheKid** [comment]
Øhhhh er der en mulig for at kunne få navne op på scoreboarded
